AllCops:
  TargetRubyVersion: 3.2

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - it
    - context
    - before
    - after
    - around
    - let
    - subject
    - let!

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 20